services:
  app:
    image: concert-api-app:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
